### ISSUE TITLE
Admin > Some CRUD operation not possible

### ISSUE THREAD

**Issue by coding-frank** [ordercloud-api/oc-accelerator#23]
Testing account: [7dvayd@gmail.com](mailto:7dvayd@gmail.com)
with following roles:
<img width="183" alt="image" src="https://github.com/user-attachments/assets/e679097f-d3a1-41b1-a074-34119b114555">

Not possible to:
- delete price-schedules 
- delete buyers 
- create promotion (edit/delete not tested) 
- create catalogs 
- create/edit/delete admins 
- create/edit/delete admin groups 
- create/edit/delete suppliers 

With FULL ACCESS all these operations should be possible.
Is there a way to block/hide those operations which are not allowed when logged in?

isAdmin & isAllowed are always true

Frank Arlt (Valtech)
frank.arlt@valtech.com

**Comment by erincdustin** [comment]
@coding-frank is the `FullAccess` role included in the `VITE_APP_ORDERCLOUD_SCOPE` value in your .env.local file?

**Comment by coding-frank** [comment]
@erincdustin No :(. It is still an empty string.
I see the docs https://github.com/ordercloud-api/oc-accelerator/blob/development/apps/admin/README.md

Which effect does it have to list some roles in VITE_APP_ORDERCLOUD_SCOPE?

**Comment by erincdustin** [comment]
@coding-frank scope is a parameter passed into the [Auth.Login() SDK method](https://ordercloud.io/learn/getting-started/making-your-first-request#retrieving-an-access-token). If defined in the .env.local file for the administrative application, it will limit the roles logged in users to what is defined in the `VITE_APP_ORDERCLOUD_SCOPE` values, regardless of whether the user has that security profile role assigned to them in OrderCloud (read more [here](https://ordercloud.io/learn/getting-started/making-your-first-request#retrieving-an-access-token))

I do think this issue is related to the user you're making requests with, however.  Can you confirm that 7dvayd@gmail.com is a buyer user? The development team has a task in progress to block buyer users from logging into the administrative application, as it is not what the application is intended for.

**Comment by coding-frank** [comment]
@erincdustin 
Yes it is a buyer user (7dvayd@gmail.com). I am using now an admin user, and all CRUD operations work! Thank you for the explanation!
