### ISSUE TITLE
Admin > Token issues

### ISSUE THREAD

**Issue by coding-frank** [ordercloud-api/oc-accelerator#8]
The token is not getting refreshed when in any details page.

The following hooks throw an 401 error after 10 minutes. Cookie has been deleted.
This kind of freezes the app, so I implemented a manual logout as temporary solution.
 
useOcResourceGet
useOcResourceList

_Possibly also effected (not tested)_
useDeleteOcResource

useOcResourceList works fine

Frank Arlt (Valtech)
frank.arlt@valtech.com

**Comment by robertsoniv** [comment]
@coding-frank thank you for bringing this to our attention. The issue has been resolved in the main branch. Our stance is that buyer users should not be logging into the admin application and vice versa (admins/suppliers in storefront). We have added new checks to the login component that will block non-seller (buyer users) from logging in, thereby avoiding any unaccounted for 403 forbidden errors on detail pages. Even if buyer users have the role ProductAdmin, they are still blocked from making changes to products through the API - there are some restrictions for certain endpoints based on what "type" of user you are.

In the future, we do plan on documenting these restricted endpoints better in the OpenAPI specification so that we may one day be able to re-enable buyer users accessing the admin application. Having that information in the spec will allow us to dynamically disable functionality that a "buyer" type user cannot perform.

Hope this helps!
-Rob
